apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ingress-manager
  name: ingress-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingress-manager
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ingress-manager
    spec:
      serviceAccountName: ingress-manager-sa
      containers:
        - image: mrblind/k8s_learning
          name: k8s-learning-vgwdz
          resources: {}
status: {}